// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FindApplications(arg1) {
  return window['go']['main']['App']['FindApplications'](arg1);
}

export function RunApplication(arg1) {
  return window['go']['main']['App']['RunApplication'](arg1);
}
